


pool: 
  vmImage: default
  
steps:
- bash: echo hello world 
- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Free Trial(d735ceb2-7ec2-482c-88fd-550ea7558e04)'
    command: 'build'